on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - run: chmod +x ../../../build.sh
      - run: ../../../build.sh
  
    
